# Generated by Django 4.2 on 2024-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='content',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('business', 'Business'), ('world', 'World'), ('politics', 'Politics'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('science', 'Science')], default='technology', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
