# Generated by Django 4.2 on 2024-12-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bbcnews_businessnews_cnnnews_politicsnews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BBCNews',
        ),
        migrations.DeleteModel(
            name='BusinessNews',
        ),
        migrations.DeleteModel(
            name='CNNNews',
        ),
        migrations.DeleteModel(
            name='PoliticsNews',
        ),
        migrations.DeleteModel(
            name='ReutersNews',
        ),
        migrations.DeleteModel(
            name='SportsNews',
        ),
        migrations.DeleteModel(
            name='TechnologyNews',
        ),
    ]
